import type { FieldGuideTopic } from "../lib/field-guide-types";

export const marketTopics: FieldGuideTopic[] = [
  {
    slug: "supply-demand",
    href: "/learning/market-economy/supply-demand",
    icon: "icarus-terminal-economy",
    title: "Supply & Demand",
    subtitle: "Commodity Availability, Demand & Market Pressure",
    description: "How supply, demand, stock levels, and local conditions shape the commodity board commanders actually trade against.",
    tags: ["Supply", "Demand", "Markets"],
    status: "available",
    signal: "MARKET: FLOW",
    overview: ["Commodity markets are snapshots of local pressure. Supply tells you what can be bought, demand tells you what a station wants, and both change as commanders and background states move the local economy."],
    keyPoints: [
      { label: "Supply", detail: "Available stock controls how much a commander can buy before prices and availability weaken." },
      { label: "Demand", detail: "Demand controls how attractive a sell station is for a given commodity." },
      { label: "Freshness", detail: "Market data is time-sensitive, so recent updates matter for route confidence." },
    ],
    fieldNotes: ["High profit per ton is less useful if stock is tiny.", "Demand can collapse after heavy hauling, especially around popular trade routes."],
    reference: [
      { label: "Buy side", value: "Supply", note: "Can the station actually fill your hold?" },
      { label: "Sell side", value: "Demand", note: "Will the destination pay well for it?" },
    ],
  },
  {
    slug: "buy-price-vs-sell-price",
    href: "/learning/market-economy/buy-price-vs-sell-price",
    icon: "icarus-terminal-route",
    title: "Buy Price vs Sell Price",
    subtitle: "Trade Route Margin & Profit Per Ton",
    description: "The basic trade-route calculation: buy low, sell high, then account for distance, cargo size, and route time.",
    tags: ["Profit", "Trade Routes", "Margin"],
    status: "available",
    signal: "ROUTE: PROFIT",
    overview: ["A trade route is a price difference with travel wrapped around it. Good tools compare buy price, sell price, supply, demand, pad size, distance, and data age instead of looking at margin alone."],
    keyPoints: [
      { label: "Margin", detail: "Sell price minus buy price gives the basic profit per unit." },
      { label: "Cargo scale", detail: "Profit per ton only matters when stock and demand can support your hold." },
      { label: "Travel cost", detail: "Supercruise distance and jump count decide how quickly that margin can be repeated." },
    ],
    fieldNotes: ["A slightly lower margin can win if the stations are close and reliable.", "Large ships must check pad size and station type before trusting a route."],
    reference: [
      { label: "Formula", value: "Sell minus buy", note: "Base profit per commodity unit." },
      { label: "Reality check", value: "Time per loop", note: "Turns raw margin into credits per hour." },
    ],
  },
  {
    slug: "economy-pairings",
    href: "/learning/market-economy/economy-pairings",
    icon: "icarus-terminal-system-orbits",
    title: "Economy Pairings",
    subtitle: "Extraction, Refinery, Agriculture & High Population",
    description: "Why certain economy combinations produce reliable trade ideas and how pairings guide commodity search.",
    tags: ["Economies", "Pairings", "Routes"],
    status: "available",
    signal: "PAIRING: ECONOMY",
    overview: ["Economy pairings are trade intuition. Extraction feeds refinery, agriculture feeds population centres, refinery feeds industrial and high-tech demand, and tourism or military economies create specialised needs."],
    keyPoints: [
      { label: "Source economy", detail: "The producer side hints at what goods may be cheap or abundant." },
      { label: "Sink economy", detail: "The consumer side hints at what goods may be demanded." },
      { label: "Route seed", detail: "Pairings create candidate routes that live market data can confirm or reject." },
    ],
    fieldNotes: ["Use pairings to search smarter, not to replace price checks.", "Faction state can override the usual behaviour of an economy pairing."],
    reference: [
      { label: "Classic chain", value: "Extraction to refinery", note: "Raw materials into processing." },
      { label: "Consumer chain", value: "Agriculture to population", note: "Food supply into demand centres." },
    ],
  },
  {
    slug: "rare-goods",
    href: "/learning/market-economy/rare-goods",
    icon: "icarus-terminal-table-index",
    title: "Rare Goods",
    subtitle: "Limited Stock, Distance Scaling & Specialist Loops",
    description: "How rare goods differ from ordinary commodities and why they reward longer-haul, low-volume trading.",
    tags: ["Rare Goods", "Trading", "Distance"],
    status: "available",
    signal: "COMMODITY: RARE",
    overview: ["Rare goods are special commodities tied to specific source locations, limited supply, and distance-based value behaviour. They are less about bulk hauling and more about route selection."],
    keyPoints: [
      { label: "Source bound", detail: "A rare good is normally bought only from its associated location." },
      { label: "Limited stock", detail: "Availability is capped, so huge cargo holds are not always useful." },
      { label: "Distance value", detail: "Profit improves when sold far enough from the source, up to practical limits." },
    ],
    fieldNotes: ["Rare goods suit smaller ships and sightseeing routes.", "They can be enjoyable but usually lose to optimised bulk trading for raw credits."],
    reference: [
      { label: "Constraint", value: "Limited stock", note: "Caps route volume." },
      { label: "Reward driver", value: "Distance", note: "Longer haul improves price behaviour." },
    ],
  },
  {
    slug: "background-simulation-effects",
    href: "/learning/market-economy/background-simulation-effects",
    icon: "icarus-terminal-warning",
    title: "Background Simulation Effects",
    subtitle: "Boom, Bust, Famine, Outbreak & War",
    description: "How BGS states influence commodity behaviour, mission boards, demand spikes, and trade opportunities.",
    tags: ["BGS", "States", "Markets"],
    status: "available",
    signal: "STATE: BGS",
    overview: ["Background Simulation states can make a familiar station behave differently. Boom, bust, famine, outbreak, war, and infrastructure states all affect demand, supply, missions, and local priorities."],
    keyPoints: [
      { label: "Boom", detail: "Often improves trade activity and can create strong market opportunities." },
      { label: "Famine or outbreak", detail: "Can drive demand for relief goods such as food or medical supplies." },
      { label: "Conflict", detail: "War and civil war shift attention toward combat, weapons, and military support." },
    ],
    fieldNotes: ["A state-driven trade can be excellent until the state ends.", "Route tools should show market update age and state context together."],
    reference: [
      { label: "Relief state", value: "Famine/outbreak", note: "Often creates emergency demand." },
      { label: "Growth state", value: "Boom", note: "Can improve market activity." },
    ],
  },
  {
    slug: "carrier-trading",
    href: "/learning/market-economy/carrier-trading",
    icon: "icarus-terminal-fullscreen",
    title: "Carrier Trading",
    subtitle: "Stock, Demand, Tariffs & Mobile Markets",
    description: "How fleet-carrier markets differ from station markets and what commanders should check before trusting a carrier trade.",
    tags: ["Carriers", "Tariffs", "Mobile Markets"],
    status: "available",
    signal: "MARKET: CARRIER",
    overview: ["Carrier markets are player-managed. Their prices, stock, demand, docking access, and location can change quickly, making verification more important than with stable station infrastructure."],
    keyPoints: [
      { label: "Owner control", detail: "Carrier owners set stock, buy orders, sell orders, and tariffs." },
      { label: "Mobility", detail: "A carrier can move away from a route, turning stale data into a trap." },
      { label: "Access", detail: "Docking permissions can restrict who can use the market." },
    ],
    fieldNotes: ["Always check carrier age and access before committing a long haul.", "Carrier trades can be excellent, but they age faster than station trades."],
    reference: [
      { label: "Volatility", value: "High", note: "Player-managed data changes quickly." },
      { label: "Key check", value: "Docking access", note: "A profitable carrier is useless if you cannot land." },
    ],
  },
];

export function findMarketTopic(slug: string): FieldGuideTopic | undefined {
  return marketTopics.find((topic) => topic.slug === slug);
}
