import type { FieldGuideTopic } from "../components/field-guide-types";

export const xenoTopics: FieldGuideTopic[] = [
  {
    slug: "thargoid-biology-ship-classes",
    href: "/learning/thargoids-guardians/thargoid-biology-ship-classes",
    icon: "icarus-terminal-warning",
    title: "Thargoid Biology & Ship Classes",
    subtitle: "Scouts, Interceptors, Hunters & Organic Technology",
    description: "A field guide to Thargoid forms, behaviour, organic ship design, and why xeno contacts feel so different from human vessels.",
    tags: ["Thargoids", "Interceptors", "Xeno"],
    status: "available",
    signal: "CONTACT: THARGOID",
    overview: ["Thargoid craft blur the line between organism and machine. Scouts, Interceptors, Hunters, and larger strategic assets behave less like conventional ships and more like specialised biological weapons systems."],
    keyPoints: [
      { label: "Scouts", detail: "Smaller, aggressive vessels often encountered in groups and conflict zones." },
      { label: "Interceptors", detail: "Large flower-like combat ships with hearts, swarms, shutdown fields, and variants." },
      { label: "Organic design", detail: "Thargoid technology uses biological motifs, caustic damage, and unfamiliar combat rules." },
    ],
    fieldNotes: ["Do not treat a xeno contact like a standard combat signal.", "Ship class identification is a survival skill before it is a lore detail."],
    reference: [
      { label: "Small contact", value: "Scout", note: "Group threat and AX entry point." },
      { label: "Major contact", value: "Interceptor", note: "Specialised AX mechanics and high danger." },
    ],
  },
  {
    slug: "guardian-ruins-structures",
    href: "/learning/thargoids-guardians/guardian-ruins-structures",
    icon: "icarus-terminal-table-index",
    title: "Guardian Ruins & Structures",
    subtitle: "Ancient Sites, Pylons, Obelisks & Blueprints",
    description: "How Guardian sites are laid out and why they matter for lore, materials, blueprints, and unlock progression.",
    tags: ["Guardians", "Ruins", "Blueprints"],
    status: "available",
    signal: "SITE: GUARDIAN",
    overview: ["Guardian locations are archaeological spaces with gameplay structure: ruins for data and lore, structures for blueprints, pylons, relic interactions, sentinels, and material gathering."],
    keyPoints: [
      { label: "Ruins", detail: "Often support obelisk scanning, lore records, and pattern data." },
      { label: "Structures", detail: "Used for module, weapon, or vessel blueprint workflows." },
      { label: "Site logic", detail: "Pylons, relics, energy charging, and sentinels create repeatable unlock puzzles." },
    ],
    fieldNotes: ["Bring an SRV and leave cargo space for artefacts if the workflow requires them.", "Guardian sites reward preparation more than improvisation."],
    reference: [
      { label: "Unlock input", value: "Blueprint", note: "Needed for Guardian technology brokers." },
      { label: "Site hazard", value: "Sentinels", note: "Automated defenders at many structures." },
    ],
  },
  {
    slug: "guardian-artefacts-materials",
    href: "/learning/thargoids-guardians/guardian-artefacts-materials",
    icon: "icarus-terminal-economy",
    title: "Guardian Artefacts and Materials",
    subtitle: "Relics, Orbs, Caskets, Pattern Data & Components",
    description: "What Guardian artefacts and materials are used for, how they differ, and why commanders gather them in loops.",
    tags: ["Artefacts", "Materials", "Unlocks"],
    status: "available",
    signal: "MATERIAL: GUARDIAN",
    overview: ["Guardian progression uses a mix of physical cargo, encoded data, manufactured-style components, and site-specific blueprints. Knowing which category you need prevents wasted site runs."],
    keyPoints: [
      { label: "Artefacts", detail: "Physical items such as relics, orbs, tablets, caskets, totems, and urns." },
      { label: "Data", detail: "Obelisk and scan rewards used for Guardian unlock requirements." },
      { label: "Components", detail: "Materials gathered from site objects and sentinel drops." },
    ],
    fieldNotes: ["Cargo artefacts and material inventory behave differently, so plan space and collection method.", "Use a checklist before leaving the site; missing one component can force a return trip."],
    reference: [
      { label: "Cargo class", value: "Artefact", note: "Takes cargo space and can attract attention." },
      { label: "Inventory class", value: "Material/data", note: "Stored outside cargo racks." },
    ],
  },
  {
    slug: "ax-combat-basics",
    href: "/learning/thargoids-guardians/ax-combat-basics",
    icon: "icarus-terminal-shield",
    title: "AX Combat Basics",
    subtitle: "Damage Types, Hearts, Swarms & Survival",
    description: "The core ideas behind anti-xeno combat and why AX builds, weapons, and tactics differ from standard combat.",
    tags: ["AX", "Combat", "Survival"],
    status: "available",
    signal: "COMBAT: AX",
    overview: ["AX combat has its own rules. Human damage expectations, shield habits, target priority, module choices, and survival decisions all shift when the opponent uses caustic damage, swarms, hearts, and shutdown fields."],
    keyPoints: [
      { label: "AX weapons", detail: "Specialised weapons are needed to damage many Thargoid targets effectively." },
      { label: "Hearts", detail: "Interceptor fights revolve around exerting and destroying hearts." },
      { label: "Survival tools", detail: "Decontamination, heat control, shutdown field neutralisers, and repair planning matter." },
    ],
    fieldNotes: ["Start with scouts or training resources before taking interceptor fights seriously.", "A standard PvE build can fail quickly in AX content."],
    reference: [
      { label: "Core weapon", value: "AX armament", note: "Needed for meaningful damage." },
      { label: "Major hazard", value: "Caustic damage", note: "Requires mitigation or cleanup." },
    ],
  },
  {
    slug: "maelstroms-titans-spire-sites",
    href: "/learning/thargoids-guardians/maelstroms-titans-spire-sites",
    icon: "icarus-terminal-planet-atmosphere",
    title: "Maelstroms, Titans & Spire Sites",
    subtitle: "War Zones, Strategic Assets & Surface Activity",
    description: "How modern Thargoid war spaces differ from ordinary xeno encounters, from Maelstrom regions to Titan and Spire activity.",
    tags: ["Maelstroms", "Titans", "Spire Sites"],
    status: "available",
    signal: "WARSPACE: XENO",
    overview: ["The Thargoid war introduced strategic geography: Maelstrom systems, Titan-related objectives, Spire sites, caustic environments, and layered activities that link space combat with surface operations."],
    keyPoints: [
      { label: "Maelstrom", detail: "Hazardous xeno-controlled region with specialised access and survival concerns." },
      { label: "Titan", detail: "Strategic Thargoid asset tied to major war progression and specialised objectives." },
      { label: "Spire site", detail: "Surface activity zone connected to Thargoid presence and war logistics." },
    ],
    fieldNotes: ["Modern xeno activity is location-specific; check current system state before travelling.", "Specialised modules and situational awareness matter more than raw jump range."],
    reference: [
      { label: "Strategic zone", value: "Maelstrom", note: "Requires preparation and context." },
      { label: "Surface zone", value: "Spire site", note: "Links xeno war to planetary operations." },
    ],
  },
  {
    slug: "human-xeno-timeline",
    href: "/learning/thargoids-guardians/human-xeno-timeline",
    icon: "icarus-terminal-notifications",
    title: "Human-Xeno Timeline",
    subtitle: "First Contacts, Guardian History & Modern War",
    description: "A high-level timeline connecting Guardian history, human discoveries, Thargoid escalation, and the current xeno war.",
    tags: ["Lore", "Timeline", "War"],
    status: "available",
    signal: "TIMELINE: XENO",
    overview: ["Human-xeno history is layered: ancient Guardian conflict, lost ruins, modern rediscovery, barnacles, incursions, superpower reactions, and full-scale war. The lore explains why the map contains so many xeno-specific regions and hazards."],
    keyPoints: [
      { label: "Ancient layer", detail: "Guardian history establishes that the Thargoid conflict predates humanity." },
      { label: "Discovery layer", detail: "Modern explorers uncovered artefacts, barnacles, probes, and ruins before open war escalated." },
      { label: "War layer", detail: "Current Thargoid activity reshapes systems, stations, rescue routes, and AX priorities." },
    ],
    fieldNotes: ["Galnet articles are often the best way to follow xeno developments in-universe.", "Lore and navigation overlap whenever permit locks, war states, or xeno sites affect route planning."],
    reference: [
      { label: "Ancient record", value: "Guardian sites", note: "Pre-human xeno context." },
      { label: "Current record", value: "Galnet and war states", note: "Modern conflict context." },
    ],
  },
];

export function findXenoTopic(slug: string): FieldGuideTopic | undefined {
  return xenoTopics.find((topic) => topic.slug === slug);
}
