import type { Engineer } from "./lib/engineer-types";

export const engineers: Engineer[] = [
  /* ── Ship engineers — Core Systems ─────────────────────────────────── */
  {
    slug: "tod-mcquinn",
    href: "/engineering/tod-mcquinn",
    name: "Tod \"The Blaster\" McQuinn",
    base: "Trophy Camp",
    system: "Wolf 397",
    planet: "Trus Madi",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Multi-cannon", maxGrade: 5 },
      { category: "Rail Gun", maxGrade: 5 },
      { category: "Cannon", maxGrade: 2 },
      { category: "Fragment Cannon", maxGrade: 2 },
    ],
  },
  {
    slug: "selene-jean",
    href: "/engineering/selene-jean",
    name: "Selene Jean",
    base: "Prospector's Rest",
    system: "Kuk",
    planet: "B 3",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Armour", maxGrade: 5 },
      { category: "Hull Reinforcement Package", maxGrade: 5 },
    ],
  },
  {
    slug: "didi-vatermann",
    href: "/engineering/didi-vatermann",
    name: "Didi Vatermann",
    base: "Vatermann LLC",
    system: "Leesti",
    planet: "1 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Shield Booster", maxGrade: 5 },
      { category: "Shield Generator", maxGrade: 3 },
    ],
  },
  {
    slug: "bill-turner",
    href: "/engineering/bill-turner",
    name: "Bill Turner",
    base: "Turner Metallics Inc",
    system: "Alioth",
    planet: "4 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-scan",
    modifications: [
      { category: "Sensors", maxGrade: 5 },
      { category: "Plasma Accelerator", maxGrade: 5 },
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "AFMU", maxGrade: 3 },
      { category: "Frame Shift Wake Scanner", maxGrade: 3 },
      { category: "Fuel Scoop", maxGrade: 3 },
      { category: "Kill Warrant Scanner", maxGrade: 3 },
      { category: "Life Support", maxGrade: 3 },
      { category: "Manifest Scanner", maxGrade: 3 },
      { category: "Refinery", maxGrade: 3 },
    ],
  },
  {
    slug: "broo-tarquin",
    href: "/engineering/broo-tarquin",
    name: "Broo Tarquin",
    base: "Broo's Legacy",
    system: "Muang",
    planet: "5 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Beam Laser", maxGrade: 5 },
      { category: "Burst Laser", maxGrade: 5 },
      { category: "Pulse Laser", maxGrade: 5 },
    ],
  },
  {
    slug: "liz-ryder",
    href: "/engineering/liz-ryder",
    name: "Liz Ryder",
    base: "Demolition Unlimited",
    system: "Eurybia",
    planet: "Makalu",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-warning",
    modifications: [
      { category: "Missile Rack", maxGrade: 5 },
      { category: "Seeker Missile Rack", maxGrade: 5 },
      { category: "Torpedo Pylon", maxGrade: 5 },
      { category: "Mine Launcher", maxGrade: 3 },
      { category: "Hull Reinforcement Package", maxGrade: 1 },
      { category: "Armour", maxGrade: 1 },
    ],
  },
  {
    slug: "hera-tani",
    href: "/engineering/hera-tani",
    name: "Hera Tani",
    base: "The Jet's Hole",
    system: "Kuwemaki",
    planet: "A 3 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-power",
    modifications: [
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "Power Plant", maxGrade: 5 },
      { category: "Power Distributor", maxGrade: 3 },
      { category: "Sensors", maxGrade: 3 },
    ],
  },
  {
    slug: "tiana-fortune",
    href: "/engineering/tiana-fortune",
    name: "Tiana Fortune",
    base: "Fortune's Loss",
    system: "Achenar",
    planet: "4 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-scan",
    modifications: [
      { category: "Manifest Scanner", maxGrade: 5 },
      { category: "Collector Limpet Controller", maxGrade: 5 },
      { category: "Frame Shift Wake Scanner", maxGrade: 5 },
      { category: "Fuel Transfer Limpet Controller", maxGrade: 5 },
      { category: "Hatch Breaker Limpet Controller", maxGrade: 5 },
      { category: "Kill Warrant Scanner", maxGrade: 5 },
      { category: "Prospector Limpet Controller", maxGrade: 5 },
      { category: "Sensors", maxGrade: 5 },
      { category: "Detailed Surface Scanner", maxGrade: 3 },
      { category: "Frame Shift Drive Interdictor", maxGrade: 3 },
    ],
  },
  {
    slug: "felicity-farseer",
    href: "/engineering/felicity-farseer",
    name: "Felicity Farseer",
    base: "Farseer Inc",
    system: "Deciat",
    planet: "6 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Frame Shift Drive", maxGrade: 5 },
      { category: "Detailed Surface Scanner", maxGrade: 3 },
      { category: "Sensors", maxGrade: 3 },
      { category: "Thrusters", maxGrade: 3 },
      { category: "Power Plant", maxGrade: 1 },
      { category: "Frame Shift Drive Interdictor", maxGrade: 1 },
      { category: "Shield Booster", maxGrade: 1 },
    ],
  },
  {
    slug: "colonel-bris-dekker",
    href: "/engineering/colonel-bris-dekker",
    name: "Colonel Bris Dekker",
    base: "Dekker's Yard",
    system: "Sol",
    planet: "Iapetus",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Frame Shift Drive Interdictor", maxGrade: 4 },
      { category: "Frame Shift Drive", maxGrade: 3 },
    ],
  },
  {
    slug: "juri-ishmaak",
    href: "/engineering/juri-ishmaak",
    name: "Juri Ishmaak",
    base: "Pater's Memorial",
    system: "Giryak",
    planet: "2 a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-warning",
    modifications: [
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "Mine Launcher", maxGrade: 5 },
      { category: "Sensors", maxGrade: 5 },
      { category: "Frame Shift Wake Scanner", maxGrade: 3 },
      { category: "Kill Warrant Scanner", maxGrade: 3 },
      { category: "Manifest Scanner", maxGrade: 3 },
      { category: "Missile Rack", maxGrade: 3 },
      { category: "Seeker Missile Rack", maxGrade: 3 },
      { category: "Torpedo Pylon", maxGrade: 3 },
    ],
  },
  {
    slug: "the-sarge",
    href: "/engineering/the-sarge",
    name: "The Sarge",
    base: "The Beach",
    system: "Beta-3 Tucani",
    planet: "2 b a",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Cannon", maxGrade: 5 },
      { category: "Collector Limpet Controller", maxGrade: 5 },
      { category: "Fuel Transfer Limpet Controller", maxGrade: 5 },
      { category: "Hatch Breaker Limpet Controller", maxGrade: 5 },
      { category: "Prospector Limpet Controller", maxGrade: 5 },
      { category: "Rail Gun", maxGrade: 3 },
    ],
  },
  {
    slug: "elvira-martuuk",
    href: "/engineering/elvira-martuuk",
    name: "Elvira Martuuk",
    base: "Long Sight Base",
    system: "Khun",
    planet: "5",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Frame Shift Drive", maxGrade: 5 },
      { category: "Shield Generator", maxGrade: 3 },
      { category: "Thrusters", maxGrade: 2 },
      { category: "Shield Cell Bank", maxGrade: 1 },
    ],
  },
  {
    slug: "the-dweller",
    href: "/engineering/the-dweller",
    name: "The Dweller",
    base: "Black Hide",
    system: "Wyrd",
    planet: "A 2",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-power",
    modifications: [
      { category: "Beam Lasers", maxGrade: 3 },
      { category: "Burst Lasers", maxGrade: 3 },
      { category: "Pulse Lasers", maxGrade: 4 },
      { category: "Power Distributor", maxGrade: 5 },
    ],
  },
  {
    slug: "lei-cheung",
    href: "/engineering/lei-cheung",
    name: "Lei Cheung",
    base: "Trader's Rest",
    system: "Laksak",
    planet: "A 1",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Shield Generator", maxGrade: 5 },
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "Sensors", maxGrade: 5 },
      { category: "Shield Booster", maxGrade: 3 },
    ],
  },
  {
    slug: "marco-qwent",
    href: "/engineering/marco-qwent",
    name: "Marco Qwent",
    base: "Qwent Research Base",
    system: "Sirius",
    planet: "Lucifer",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-power",
    modifications: [
      { category: "Power Plant", maxGrade: 4 },
      { category: "Power Distributor", maxGrade: 3 },
    ],
  },
  {
    slug: "professor-palin",
    href: "/engineering/professor-palin",
    name: "Professor Palin",
    base: "Abel Laboratory",
    system: "Arque",
    planet: "4 e",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Thrusters", maxGrade: 5 },
      { category: "Frame Shift Drive", maxGrade: 3 },
    ],
  },
  {
    slug: "zacariah-nemo",
    href: "/engineering/zacariah-nemo",
    name: "Zacariah Nemo",
    base: "Nemo Cyber Party Base",
    system: "Yoru",
    planet: "4",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Fragment Cannon", maxGrade: 5 },
      { category: "Multi-cannon", maxGrade: 3 },
      { category: "Plasma Accelerator", maxGrade: 2 },
    ],
  },
  {
    slug: "lori-jameson",
    href: "/engineering/lori-jameson",
    name: "Lori Jameson",
    base: "Jameson Base",
    system: "Shinrarta Dezhra",
    planet: "A 1",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-scan",
    modifications: [
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "Sensors", maxGrade: 5 },
      { category: "AFMU", maxGrade: 4 },
      { category: "Fuel Scoop", maxGrade: 4 },
      { category: "Life Support", maxGrade: 4 },
      { category: "Refinery", maxGrade: 4 },
      { category: "Frame Shift Wake Scanner", maxGrade: 3 },
      { category: "Manifest Scanner", maxGrade: 3 },
      { category: "Shield Cell Bank", maxGrade: 3 },
    ],
  },
  {
    slug: "ram-tah",
    href: "/engineering/ram-tah",
    name: "Ram Tah",
    base: "Phoenix Base",
    system: "Meene",
    planet: "AB 5 d",
    region: "core",
    discipline: "ship",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Chaff Launcher", maxGrade: 5 },
      { category: "ECM", maxGrade: 5 },
      { category: "Heat Sink Launcher", maxGrade: 5 },
      { category: "Point Defence", maxGrade: 5 },
      { category: "Collector Limpet Controller", maxGrade: 4 },
      { category: "Fuel Transfer Limpet Controller", maxGrade: 4 },
      { category: "Prospector Limpet Controller", maxGrade: 4 },
      { category: "Hatch Breaker Limpet Controller", maxGrade: 3 },
    ],
  },

  /* ── Ship engineers — Colonia Region ───────────────────────────────── */
  {
    slug: "etienne-dorn",
    href: "/engineering/etienne-dorn",
    name: "Etienne Dorn",
    base: "Kraken's Retreat",
    system: "Los",
    planet: "A 2 b",
    region: "colonia",
    discipline: "ship",
    icon: "icarus-terminal-power",
    modifications: [
      { category: "Detailed Surface Scanner", maxGrade: 5 },
      { category: "Frame Shift Wake Scanner", maxGrade: 5 },
      { category: "Kill Warrant Scanner", maxGrade: 5 },
      { category: "Life Support", maxGrade: 5 },
      { category: "Manifest Scanner", maxGrade: 5 },
      { category: "Plasma Accelerator", maxGrade: 5 },
      { category: "Power Distributor", maxGrade: 5 },
      { category: "Power Plant", maxGrade: 5 },
      { category: "Sensors", maxGrade: 5 },
      { category: "Rail Gun", maxGrade: 5 },
    ],
  },
  {
    slug: "marsha-hicks",
    href: "/engineering/marsha-hicks",
    name: "Marsha Hicks",
    base: "The Watchtower",
    system: "Tir",
    planet: "A 2",
    region: "colonia",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Cannon", maxGrade: 5 },
      { category: "Fragment Cannon", maxGrade: 5 },
      { category: "Fuel Scoop", maxGrade: 5 },
      { category: "Fuel Transfer Limpet Controller", maxGrade: 5 },
      { category: "Hatch Breaker Limpet Controller", maxGrade: 5 },
      { category: "Multi-cannon", maxGrade: 5 },
      { category: "Prospector Limpet Controller", maxGrade: 5 },
      { category: "Refinery", maxGrade: 5 },
    ],
  },
  {
    slug: "mel-brandon",
    href: "/engineering/mel-brandon",
    name: "Mel Brandon",
    base: "The Brig",
    system: "Luchtaine",
    planet: "A 1 c",
    region: "colonia",
    discipline: "ship",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Beam Laser", maxGrade: 5 },
      { category: "Burst Laser", maxGrade: 5 },
      { category: "Pulse Laser", maxGrade: 5 },
      { category: "Shield Generator", maxGrade: 5 },
      { category: "Thrusters", maxGrade: 5 },
      { category: "Shield Booster", maxGrade: 5 },
      { category: "Frame Shift Drive", maxGrade: 5 },
      { category: "Frame Shift Drive Interdictor", maxGrade: 5 },
      { category: "Shield Cell Bank", maxGrade: 4 },
    ],
  },
  {
    slug: "petra-olmanova",
    href: "/engineering/petra-olmanova",
    name: "Petra Olmanova",
    base: "Sanctuary",
    system: "Asura",
    planet: "1 a",
    region: "colonia",
    discipline: "ship",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Armour", maxGrade: 5 },
      { category: "AFMU", maxGrade: 5 },
      { category: "Chaff Launcher", maxGrade: 5 },
      { category: "ECM", maxGrade: 5 },
      { category: "Heat Sink Launcher", maxGrade: 5 },
      { category: "Hull Reinforcement Package", maxGrade: 5 },
      { category: "Mine Launcher", maxGrade: 5 },
      { category: "Missile Rack", maxGrade: 5 },
      { category: "Point Defence", maxGrade: 5 },
      { category: "Seeker Missile Rack", maxGrade: 5 },
      { category: "Torpedo Pylon", maxGrade: 5 },
    ],
  },

  /* ── Ship engineers — Witch Head Nebula ────────────────────────────── */
  {
    slug: "chloe-sedesi",
    href: "/engineering/chloe-sedesi",
    name: "Chloe Sedesi",
    base: "Cinder Dock",
    system: "Shenve",
    planet: "A 6",
    region: "witch-head",
    discipline: "ship",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Thrusters", maxGrade: 5 },
      { category: "Frame Shift Drive", maxGrade: 3 },
    ],
  },

  /* ── Pilot equipment engineers — Core Systems ──────────────────────── */
  {
    slug: "domino-green",
    href: "/engineering/domino-green",
    name: "Domino Green",
    base: "The Jackrabbit",
    system: "Orishis",
    planet: "4",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-scan",
    modifications: [
      { category: "Enhanced Tracking" },
      { category: "Extra Backpack Capacity" },
      { category: "Reduced Tool Battery Consumption" },
      { category: "Greater Range" },
      { category: "Stability" },
    ],
  },
  {
    slug: "hero-ferrari",
    href: "/engineering/hero-ferrari",
    name: "Hero Ferrari",
    base: "Nevermore Terrace",
    system: "Siris",
    planet: "5 c",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-planet-lander",
    modifications: [
      { category: "Improved Jump Assist" },
      { category: "Increased Air Reserves" },
      { category: "Faster Handling" },
      { category: "Noise Suppressor" },
    ],
  },
  {
    slug: "jude-navarro",
    href: "/engineering/jude-navarro",
    name: "Jude Navarro",
    base: "Marshall's Drift",
    system: "Aurai",
    planet: "1 a",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-combat",
    modifications: [
      { category: "Added Melee Damage" },
      { category: "Damage Resistance" },
      { category: "Extra Ammo Capacity" },
      { category: "Magazine Size" },
      { category: "Reload Speed" },
    ],
  },
  {
    slug: "kit-fowler",
    href: "/engineering/kit-fowler",
    name: "Kit Fowler",
    base: "The Last Call",
    system: "Capoya",
    planet: "2",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Added Melee Damage" },
      { category: "Extra Ammo Capacity" },
      { category: "Faster Shield Regen" },
      { category: "Magazine Size" },
      { category: "Stowed Reloading" },
    ],
  },
  {
    slug: "oden-geiger",
    href: "/engineering/oden-geiger",
    name: "Oden Geiger",
    base: "Ankh's Promise",
    system: "Candiaei",
    planet: "9 c",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-signal",
    modifications: [
      { category: "Enhanced Tracking" },
      { category: "Improved Battery Capacity" },
      { category: "Night Vision" },
      { category: "Scope" },
      { category: "Stability" },
    ],
  },
  {
    slug: "terra-velasquez",
    href: "/engineering/terra-velasquez",
    name: "Terra Velasquez",
    base: "Rascal's Choice",
    system: "Shou Xing",
    planet: "1",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Combat Movement Speed" },
      { category: "Increased Air Reserves" },
      { category: "Increased Sprint Duration" },
      { category: "Improved Hip Fire Accuracy" },
      { category: "Noise Suppressor" },
    ],
  },
  {
    slug: "uma-laszlo",
    href: "/engineering/uma-laszlo",
    name: "Uma Laszlo",
    base: "Laszlo's Resolve",
    system: "Xuane",
    planet: "A 3",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-shield",
    modifications: [
      { category: "Damage Resistance" },
      { category: "Faster Shield Regen" },
      { category: "Headshot Damage" },
      { category: "Reload Speed" },
      { category: "Stowed Reloading" },
    ],
  },
  {
    slug: "wellington-beck",
    href: "/engineering/wellington-beck",
    name: "Wellington Beck",
    base: "Beck Facility",
    system: "Jolapa",
    planet: "6 a",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-power",
    modifications: [
      { category: "Extra Backpack Capacity" },
      { category: "Improved Battery Capacity" },
      { category: "Reduced Tool Battery Consumption" },
      { category: "Greater Range" },
      { category: "Scope" },
    ],
  },
  {
    slug: "yarden-bond",
    href: "/engineering/yarden-bond",
    name: "Yarden Bond",
    base: "Salamander Bank",
    system: "Bayan",
    planet: "7 b",
    region: "core",
    discipline: "pilot",
    icon: "icarus-terminal-sound",
    modifications: [
      { category: "Combat Movement Speed" },
      { category: "Improved Jump Assist" },
      { category: "Quieter Footsteps" },
      { category: "Audio Masking" },
      { category: "Faster Handling" },
      { category: "Improved Hip Fire Accuracy" },
    ],
  },

  /* ── Pilot equipment engineers — Colonia Region ────────────────────── */
  {
    slug: "baltanos",
    href: "/engineering/baltanos",
    name: "Baltanos",
    base: "The Divine Apparatus",
    system: "Deriso",
    planet: "3 a",
    region: "colonia",
    discipline: "pilot",
    icon: "icarus-terminal-route",
    modifications: [
      { category: "Combat Movement Speed" },
      { category: "Improved Jump Assist" },
      { category: "Increased Air Reserves" },
      { category: "Increased Sprint Duration" },
      { category: "Faster Handling" },
      { category: "Improved Hip Fire Accuracy" },
      { category: "Noise Suppressor" },
    ],
  },
  {
    slug: "eleanor-bresa",
    href: "/engineering/eleanor-bresa",
    name: "Eleanor Bresa",
    base: "Bresa Modifications",
    system: "Desy",
    planet: "7 a",
    region: "colonia",
    discipline: "pilot",
    icon: "icarus-terminal-target",
    modifications: [
      { category: "Added Melee Damage" },
      { category: "Damage Resistance" },
      { category: "Extra Ammo Capacity" },
      { category: "Faster Shield Regen" },
      { category: "Magazine Size" },
      { category: "Reload Speed" },
      { category: "Stowed Reloading" },
    ],
  },
  {
    slug: "rosa-dayette",
    href: "/engineering/rosa-dayette",
    name: "Rosa Dayette",
    base: "Rosa's Shop",
    system: "Kojeara",
    planet: "4 b",
    region: "colonia",
    discipline: "pilot",
    icon: "icarus-terminal-scan",
    modifications: [
      { category: "Enhanced Tracking" },
      { category: "Extra Backpack Capacity" },
      { category: "Improved Battery Capacity" },
      { category: "Reduced Tool Battery Consumption" },
      { category: "Greater Range" },
      { category: "Scope" },
      { category: "Stability" },
    ],
  },
  {
    slug: "yi-shen",
    href: "/engineering/yi-shen",
    name: "Yi Shen",
    base: "Eidolon Hold",
    system: "Einheriar",
    planet: "1 a",
    region: "colonia",
    discipline: "pilot",
    icon: "icarus-terminal-signal",
    modifications: [
      { category: "Night Vision" },
      { category: "Quieter Footsteps" },
      { category: "Audio Masking" },
      { category: "Headshot Damage" },
    ],
  },
];

export function findEngineer(slug: string): Engineer | undefined {
  return engineers.find((engineer) => engineer.slug === slug);
}
