import type { FieldGuideTopic } from "../components/field-guide-types";

export const engineeringTopics: FieldGuideTopic[] = [
  {
    slug: "material-types",
    href: "/learning/engineering-materials/material-types",
    icon: "icarus-terminal-table-index",
    title: "Material Types",
    subtitle: "Raw, Manufactured & Encoded",
    description: "The three engineering material categories and why each one comes from different activities, inventories, and gathering loops.",
    tags: ["Raw", "Manufactured", "Encoded"],
    status: "available",
    signal: "MATERIAL: TYPES",
    overview: ["Engineering materials are not cargo. Raw, manufactured, and encoded materials sit in separate inventories, come from different activities, and feed different blueprint requirements."],
    keyPoints: [
      { label: "Raw", detail: "Planetary and mining-adjacent materials used heavily for engineering and synthesis." },
      { label: "Manufactured", detail: "Components from ships, signal sources, mission rewards, and salvage." },
      { label: "Encoded", detail: "Data from scans, wakes, beacons, terminals, and mission rewards." },
    ],
    fieldNotes: ["The right farming method depends on material category first.", "A commander can be rich in one category and completely blocked in another."],
    reference: [
      { label: "Physical minerals", value: "Raw", note: "Often gathered on surfaces." },
      { label: "Data inventory", value: "Encoded", note: "Gathered by scanning and data sources." },
    ],
  },
  {
    slug: "grades-material-traders",
    href: "/learning/engineering-materials/grades-material-traders",
    icon: "icarus-terminal-economy",
    title: "Grades & Material Traders",
    subtitle: "Rarity, Exchange Rates & Cross-Trading",
    description: "How material grades work and how traders turn excess materials into the ones a commander actually needs.",
    tags: ["Grades", "Traders", "Exchange"],
    status: "available",
    signal: "TRADE: MATERIAL",
    overview: ["Materials have grades that represent rarity and exchange value. Material Traders let commanders convert within a category, usually at a loss, which turns broad gathering into targeted progress."],
    keyPoints: [
      { label: "Grade", detail: "Higher grades are rarer and more valuable in trader exchange rates." },
      { label: "Trader type", detail: "Raw, manufactured, and encoded traders handle their own categories." },
      { label: "Trade loss", detail: "Conversion costs mean direct gathering is often better for repeated needs." },
    ],
    fieldNotes: ["Gather high-grade materials when possible, then trade down for lower-grade needs.", "Cross-category trading is not available, so category planning matters."],
    reference: [
      { label: "Best use", value: "Trade down", note: "High grade to lower grade is usually efficient." },
      { label: "Boundary", value: "Same category", note: "Traders do not merge raw, manufactured, and encoded pools." },
    ],
  },
  {
    slug: "blueprint-grades-experimental-effects",
    href: "/learning/engineering-materials/blueprint-grades-experimental-effects",
    icon: "icarus-terminal-fullscreen",
    title: "Blueprint Grades & Experimental Effects",
    subtitle: "Modification Levels, Tradeoffs & Specials",
    description: "How module engineering progresses through grades and why experimental effects define many final builds.",
    tags: ["Blueprints", "Experimentals", "Modules"],
    status: "available",
    signal: "BLUEPRINT: MODULE",
    overview: ["Engineering blueprints improve modules through grades, but each modification has tradeoffs. Experimental effects add a final special property that often defines the purpose of the finished module."],
    keyPoints: [
      { label: "Grades", detail: "Higher grades increase the effect but cost more and can deepen tradeoffs." },
      { label: "Tradeoffs", detail: "A blueprint may improve one stat while hurting mass, integrity, heat, power, or draw." },
      { label: "Experimental", detail: "A special effect applied after engineering that gives the module its final role." },
    ],
    fieldNotes: ["A build is a system; do not engineer one module without checking heat, power, mass, and distributor load.", "Experimental effects are easy to forget and painful to travel back for."],
    reference: [
      { label: "Progression", value: "Grade 1 to 5", note: "Increasing effect and material cost." },
      { label: "Final touch", value: "Experimental", note: "Special effect on top of the blueprint." },
    ],
  },
  {
    slug: "guardian-unlocks",
    href: "/learning/engineering-materials/guardian-unlocks",
    icon: "icarus-terminal-route",
    title: "Guardian Unlocks",
    subtitle: "Blueprints, Tech Brokers & Hybrid Equipment",
    description: "How Guardian technology unlocks work and why Guardian modules and weapons sit alongside engineering progression.",
    tags: ["Guardian", "Unlocks", "Tech Broker"],
    status: "available",
    signal: "UNLOCK: GUARDIAN",
    overview: ["Guardian unlocks use site blueprints, Guardian materials, artefacts, and technology brokers. Once unlocked, many items become purchasable rather than re-crafted every time."],
    keyPoints: [
      { label: "Blueprints", detail: "Site-specific scans or events produce blueprint fragments for unlocks." },
      { label: "Materials", detail: "Guardian components, pattern data, and artefacts complete broker requirements." },
      { label: "Role", detail: "Guardian FSD boosters, modules, fighters, and AX weapons open specialised builds." },
    ],
    fieldNotes: ["Bring the right cargo and SRV loadout before travelling to a Guardian site.", "Unlock checklists save enormous time because one missing item blocks the broker hand-in."],
    reference: [
      { label: "Turn-in", value: "Technology broker", note: "Unlocks Guardian items." },
      { label: "Popular item", value: "FSD booster", note: "Major range boost for many ships." },
    ],
  },
  {
    slug: "suit-weapon-engineering",
    href: "/learning/engineering-materials/suit-weapon-engineering",
    icon: "icarus-terminal-shield",
    title: "Suit and Weapon Engineering",
    subtitle: "Odyssey Upgrades, Mods & Settlement Materials",
    description: "How Odyssey suit and weapon engineering differs from ship engineering and why settlement materials matter.",
    tags: ["Odyssey", "Suits", "Weapons"],
    status: "available",
    signal: "BLUEPRINT: SUIT",
    overview: ["On-foot engineering uses suits, weapons, upgrades, mods, data, goods, and assets gathered through settlement gameplay. The loop is more inventory-specific than most ship engineering."],
    keyPoints: [
      { label: "Upgrades", detail: "Suits and weapons progress through grades that improve base performance." },
      { label: "Mods", detail: "Permanent modifications define the role, such as stealth, capacity, battery, audio masking, or handling." },
      { label: "Settlement loot", detail: "Assets, goods, and data are gathered from Odyssey locations and missions." },
    ],
    fieldNotes: ["Plan mods before applying them, because on-foot modification choices are not casual swaps.", "Settlement legality matters; some gathering loops create fines, bounties, or reputation consequences."],
    reference: [
      { label: "Inventory", value: "Goods/assets/data", note: "Odyssey material categories." },
      { label: "Build choice", value: "Suit mods", note: "Define role and workflow." },
    ],
  },
  {
    slug: "efficient-gathering-loops",
    href: "/learning/engineering-materials/efficient-gathering-loops",
    icon: "icarus-terminal-scan",
    title: "Efficient Gathering Loops",
    subtitle: "Signals, Surfaces, Scans & Mission Rewards",
    description: "How commanders plan material gathering without turning every engineering project into a random grind.",
    tags: ["Gathering", "Loops", "Planning"],
    status: "available",
    signal: "LOOP: MATERIAL",
    overview: ["Efficient gathering starts with the blueprint list, not the farm location. Know the category and grade you need, pick a loop that produces it, then use traders to smooth the leftovers."],
    keyPoints: [
      { label: "Start with needs", detail: "Blueprint shopping lists prevent unfocused gathering." },
      { label: "Choose loop", detail: "Use surfaces for raw, signals and salvage for manufactured, scans for encoded, and settlements for Odyssey." },
      { label: "Trade cleanup", detail: "Material traders convert surplus into missing items after the main loop." },
    ],
    fieldNotes: ["Gathering is faster when the ship, SRV, and mission stack are chosen for the material type.", "Avoid maxing random bins; inventory caps can waste future drops."],
    reference: [
      { label: "Planning unit", value: "Blueprint list", note: "Determines what to gather." },
      { label: "Cleanup tool", value: "Material trader", note: "Converts surplus after targeted gathering." },
    ],
  },
];

export function findEngineeringTopic(slug: string): FieldGuideTopic | undefined {
  return engineeringTopics.find((topic) => topic.slug === slug);
}
